"""Generated ODD / TRACE skeletons and the GOAL §8 reporting gate.

``stewardsim odd`` and ``stewardsim trace`` list every registered
``Parameter.name``. Names come from the last in-process study run when
one exists, plus live Parameter fields on Policy, AdherenceModel,
Determinant, and Importation, plus fixture ``world.yaml`` Parameters
when those files are loadable. Adding a Parameter in code or fixtures
changes TRACE.

``stewardsim validate`` writes the AT ledger. ``stewardsim report``
refuses Tier 2/3 while AT-5 is not green. Fixture directories are
software proof, not a paper result.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, get_args, get_origin

import yaml

from stewardsim.importation import Importation
from stewardsim.params import Parameter
from stewardsim.pathogen import Determinant
from stewardsim.policy import AdherenceModel, Policy

_REGISTRY_TYPES = (Policy, AdherenceModel, Determinant, Importation)
_WORLD_NAME = "world.yaml"
_GATE_NAME = "at_gate.json"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _mentions_parameter(annotation: Any) -> bool:
    if annotation is Parameter:
        return True
    if annotation is None or annotation is type(None):
        return False
    if isinstance(annotation, str):
        return "Parameter" in annotation
    origin = get_origin(annotation)
    if origin is None:
        name = getattr(annotation, "__name__", "")
        if name == "Parameter":
            return True
        forward = getattr(annotation, "__forward_arg__", None)
        return isinstance(forward, str) and "Parameter" in forward
    return any(_mentions_parameter(arg) for arg in get_args(annotation))


def parameter_field_names(model_cls: type) -> tuple[str, ...]:
    """Parameter-typed field names on a live Pydantic model class."""
    fields = getattr(model_cls, "model_fields", None)
    if not fields:
        return ()
    names = [
        name
        for name, field in fields.items()
        if _mentions_parameter(getattr(field, "annotation", None))
    ]
    return tuple(names)


def parameter_names_from_mapping(obj: Any) -> tuple[str, ...]:
    """Collect ``Parameter.name`` values from a loaded mapping (e.g. YAML)."""
    found: list[str] = []
    if isinstance(obj, dict):
        name = obj.get("name")
        if (
            isinstance(name, str)
            and "provenance" in obj
            and "distribution" in obj
        ):
            found.append(name)
        for value in obj.values():
            found.extend(parameter_names_from_mapping(value))
    elif isinstance(obj, (list, tuple)):
        for item in obj:
            found.extend(parameter_names_from_mapping(item))
    return tuple(found)


def type_registry_parameter_names() -> tuple[str, ...]:
    names: list[str] = []
    for model in _REGISTRY_TYPES:
        names.extend(parameter_field_names(model))
    return tuple(dict.fromkeys(names))


def _fixture_world_paths() -> list[Path]:
    candidates = (
        _repo_root() / "tests" / "fixtures" / "shape" / _WORLD_NAME,
        Path.cwd() / "tests" / "fixtures" / "shape" / _WORLD_NAME,
    )
    found: list[Path] = []
    seen: set[Path] = set()
    for path in candidates:
        try:
            resolved = path.resolve()
        except OSError:
            continue
        if resolved in seen or not path.is_file():
            continue
        seen.add(resolved)
        found.append(path)
    return found


def fixture_parameter_names() -> tuple[str, ...]:
    names: list[str] = []
    for path in _fixture_world_paths():
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, yaml.YAMLError):
            continue
        names.extend(parameter_names_from_mapping(data))
    return tuple(dict.fromkeys(names))


def last_run_parameter_names() -> tuple[str, ...]:
    import stewardsim.runner as runner

    run = runner._LAST_RUN
    if run is None:
        return ()
    return tuple(param.name for param in run.parameters)


def registered_parameter_names() -> tuple[str, ...]:
    """Last-run names if present, then live type + fixture registries."""
    names: list[str] = []
    names.extend(last_run_parameter_names())
    names.extend(type_registry_parameter_names())
    names.extend(fixture_parameter_names())
    return tuple(dict.fromkeys(names))


def emit_odd() -> str:
    """ODD protocol skeleton generated from live Parameter registries."""
    names = registered_parameter_names()
    lines = [
        "# ODD protocol skeleton (generated from live registries)",
        "",
        "Generated by `stewardsim odd`. Do not edit by hand;",
        "adding a Parameter in code or fixtures changes this document.",
        "",
        "## 1. Purpose",
        "",
        "stewardsim Slice-0 restriction-loop: forced formulary tape →",
        "policy ∘ feasibility ∘ adherence → exposure-dependent selection",
        "→ determinant frequencies.",
        "",
        "## 2. Entities, state variables, and scales",
        "",
        "Host, Policy, Feasibility, AdherenceModel, Determinant, Importation,",
        "ForcedRestriction. Discrete days.",
        "",
        "## 3. Process overview and scheduling",
        "",
        "Daily: restrict → policy → feasibility → adherence → exposure → selection.",
        "",
        "## 4. Design concepts",
        "",
        "Provenance-tagged Parameters. No unforced policy search in Slice-0.",
        "",
        "## 5. Initialization",
        "",
        "Study YAML + structural fixtures. Incidence is a Parameter.",
        "",
        "## 6. Input data",
        "",
        "Restriction tape and host / world.yaml fixtures.",
        "No invented observed series.",
        "",
        "## 7. Submodels / Parameters",
        "",
        "Registered Parameter.name values:",
        "",
    ]
    for name in names:
        lines.append(f"- {name}")
    lines.append("")
    return "\n".join(lines)


def emit_trace() -> str:
    """TRACE evaluation skeleton generated from live Parameter registries."""
    names = registered_parameter_names()
    lines = [
        "# TRACE evaluation skeleton (generated from live registries)",
        "",
        "Generated by `stewardsim trace`. Documentation cannot drift from",
        "implementation: every registered Parameter.name is listed.",
        "",
        "## Problem formulation",
        "",
        "Restriction-loop coupling. Fixture directories are software proof,",
        "not a paper result.",
        "",
        "## Model description",
        "",
        "See ODD. Parameters below are live from Policy, AdherenceModel,",
        "Determinant, Importation model_fields, last run, and fixture",
        f"{_WORLD_NAME} if loadable.",
        "",
        "## Data evaluation",
        "",
        "AT-12 event files are user-supplied. Missing files ⇒ BLOCK.",
        "No invented AT-12 numbers.",
        "",
        "## Implementation verification",
        "",
        "Analytic ATs recorded in the AT gate file. AT-5 is not_run in Slice-0.",
        "",
        "## Parameters",
        "",
    ]
    for name in names:
        lines.append(f"- name: {name}")
    lines.append("")
    return "\n".join(lines)


def write_at_gate(path: str | Path | None = None) -> Path:
    """Write per-AT status. Default: ``output/at_gate.json`` under cwd."""
    from stewardsim.validate import evaluate_at_gate

    target = Path(path) if path is not None else Path("output") / _GATE_NAME
    target.parent.mkdir(parents=True, exist_ok=True)
    gate = evaluate_at_gate()
    target.write_text(
        json.dumps(gate, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return target


def _load_or_evaluate_gate() -> dict[str, str]:
    from stewardsim.validate import evaluate_at_gate

    path = Path("output") / _GATE_NAME
    if path.is_file():
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError):
            payload = None
        if isinstance(payload, dict):
            return {str(key): str(value) for key, value in payload.items()}
    return evaluate_at_gate()


def report(*, tier: int | None = None) -> None:
    """Emit a report or refuse. Tier 2/3 require AT-5 == pass."""
    requested = {tier} if tier is not None else {1, 2, 3}
    gate = _load_or_evaluate_gate()
    at5 = gate.get("AT-5", "not_run")
    if requested & {2, 3} and at5 != "pass":
        print(
            "GOAL §8 reporting gate: AT-5 is "
            f"{at5}; Tier 2/3 results may not be reported. "
            "Fixture directories are software proof, not a paper result.",
            file=sys.stderr,
        )
        raise SystemExit(1)
    print("Tier 1 analytic ledger only. Fixture directories are not a paper result.")
    for at_id in sorted(gate):
        print(f"{at_id}: {gate[at_id]}")
